### ISSUE TITLE
PointClouds

### ISSUE THREAD

**Issue by L-Reichardt** [romainloiseau/HelixNet#1]
Hello,

I am trying to work with the pointclouds, reading them with the functions in helixnet/laserscan/helixnet.py. After opening them I am visualizing them in Open3D, seeing that they are shifted in xyz-directions depending on the frame. 
Is there any "official" way to reverse this or to obtain the raw LiDAR data?

Best Regards,
L

**Comment by romainloiseau** [comment]
Hello,

In our dataset, each point is associated with the 9 following values: (1-3) Cartesian coordinates with the first point at (0,0,0), (4-6) cylindrical coordinate relative to the sensor at the time of acquisition, (7) intensity, (8) fiber index, and (9) packet
output time. This is the raw LiDAR data. If you want to get each frames centered on the same referential, you can refer to indices (4-6).

**Comment by L-Reichardt** [comment]
@romainloiseau Thank you very much. I should have read the source code more thoroughly.

For completeness, the transformation r,t,z -> x,y,z can be found in `def cyl2cart` provided in the repository [here](https://github.com/romainloiseau/HelixNet/blob/02b6447743242effe1a9a128ebb5adb0ef6731cf/helixnet/utils/cylindric.py#L4).
