### ISSUE TITLE
Pose from local to world frame

### ISSUE THREAD

**Issue by thomas-enxuli** [romainloiseau/HelixNet#2]
Hi there,
Thanks for the amazing work to share the dataset and the devkit! 

Questions regarding the input data of the LiDAR point cloud:
If I understand correctly, the input data has 9 channels where channels `0,1,2` are the `xyz` coordinates in the world frame where the origin of the world frame is consistent across each sequence, and channels `3,4,5` are the cylindrical coordinates in the LiDAR local frame. And the pose from local to world could be computed by computing a 3D rigid transformation from `cyl2cart(channels 3,4,5)` to channels `0,1,2`. Is this correct? And is there instance label for the movable things in the scene? Thanks in advance!

Best,
Thomas

**Comment by romainloiseau** [comment]
Hi,

Exactly, as explained in the paper, "Each point is associated with the 9 following values: (1-3) Cartesian coordinates in a fixed frame of a reference, (4-6) cylindrical coordinate relative to the sensor at the time of acquisition, (7) intensity, (8) fiber index, and (9) packet output time." I will add this in the github readme

We don't have instances in this dataset.

Best,

Romain Loiseau
