### ISSUE TITLE
How to produce results in Table 3

### ISSUE THREAD

**Issue by 22nicolet** [romainloiseau/HelixNet#3]
Hello,

To produce the IoU results by class in Table 3, are there any changes I need to make to the yaml files? After running the pretrained model the iou value comes out to be a mean constant instead of a nine-value IoU array by class. 

Also, is there a reason the transformer block only uses key and value vectors but not a query vector?

Thanks!

**Comment by romainloiseau** [comment]
This issue relates to the repo https://github.com/romainloiseau/Helix4D
Please open a new issue in the good repository so that I can answer
